apiVersion: 1
contactPoints:
  - orgId: 1
    name: mrp-oncall
    receivers:
      - uid: mrp-oncall-email
        type: email
        settings:
          addresses: oncall@example.com
          singleEmail: true
