apiVersion: 1
datasources:
  - name: MRP-Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: mrp
    user: mrp
    secureJsonData: { password: mrp }
    jsonData: { sslmode: disable, postgresVersion: 1600, timescaledb: false }
